seed: 0
use_mixed_precision: true
checkpoint: null
data_config:
  min_length: 40
  max_length: 196
loop_config:
  batch_size: 128
  eval_steps: 100
  total_steps: 600000
  learning_rate: 0.0001
  weight_decay: 1.0e-07
  warmup_steps: 5000
  grad_accum_steps: 0
