FROM nvidia/cuda:12.0.1-cudnn8-devel-ubuntu22.04

RUN pip install "jax[cuda12_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
RUN pip install tensorflow tensorflow_datasets
